### PR TITLE
Fix missing full stop.

### PR DESCRIPTION
**Pull request by MicroDroid**

### CODE REVIEW

**Comment by JeDaYoshi** [comment]
nice PR

**Comment by neoncloth** [comment]
There isn't supposed to be a full stop and the end of categories before a header. Reverting...

**Comment by neoncloth** [comment]
There isn't supposed to be a full stop and the end of categories before a header

**Comment by JeDaYoshi** [comment]
you know you didn't PR it right

**Comment by MicroDroid** [comment]
@neoncloth 

A full stop *should* be used whenever there is a concrete sentence. For example in lists, if you have a list as such:
- Oranges
- Apples

You see here we did not use a full stop since it isn't a concrete sentence. However, in this other list we *would* use a full stop:

- I ate an apple yesterday.
- He had drunk some coke.

Given that the note contains a concrete sentence, a full stop *should* be used. You see I used "should" because eventually it's all about consistency and stylistic choices, however, since the README does use full stops properly, it makes sense for the note as well to have a full stop.

Thus, this PR is a more correct version of the README. [Here](https://english.stackexchange.com/questions/108385/should-i-use-a-full-stop-at-the-end-of-text-in-a-table/110164) you can get more information about the subject.

Thanks.

**Pull request merged**
